GUIDE.md, Makefile, cmd/es-node/main.go
Related issue: https://github.com/ethstorage/es-node/issues/54
New build:
```
root@goquarkchain-test:~/github.com/ethstorage/es-node# make 
env GO111MODULE=on GOOS= GOARCH= go1.20.10 build -v -ldflags "-X main.GitCommit=eeff04cbffb524bda291abd7006d2b98c43ccbf9 -X main.GitDate=1699671584 -X main.Meta=dev -X 'main.BuildTime=Sat Nov 11 03:03:05 UTC 2023'" -o ./cmd/es-node/es-node ./cmd/es-node/
github.com/ethstorage/go-ethstorage/cmd/es-node
root@goquarkchain-test:~/github.com/ethstorage/es-node# ./cmd/es-node/es-node -v
EthStorage node version v0.1.1-81e083e9-1699873072
Build date: Mon Nov 13 10:59:47 UTC 2023
System version: amd64/linux
Golang version: go1.20.10
```
=> add make file to make the built es-node versoin contain 

run.sh
This allows us to run "./run.sh --p2p.ip.advertise=xxxx" with extra argument.
=> run.sh is runnable and accepts extra args

ethstorage/miner/worker.go
To address https://github.com/ethstorage/es-node/issues/87, print summary in `assignTasks` and result in `mineTask` shard0. 
Now log be like:
```
INFO [11-24|03:09:34.125] Mining tasks assigned                    shard=0 threads=4 block=168,775 nonces=1,048,576
INFO [11-24|03:09:34.897] The nonces are exhausted in this slot, waiting for the next block samplingTime=0.8s shard=0 block=168,775
```
Or, 
```
INFO [11-24|04:40:24.534] Mining tasks assigned                    shard=0 threads=16 block=168,930 nonces=1,048,576
WARN [11-24|04:40:36.535] Mining tasks timed out                   shard=0 block=168,930 noncesTried=574064(54.7%)
```
=> Task summary output to log

ethstorage/downloader/downloader.go, ethstorage/flags/p2p_flags.go, ethstorage/node/node.go, ethstorage/node/node_mine_test.go, ethstorage/p2p/cli/load_config.go, ethstorage/p2p/node.go, ethstorage/p2p/protocol/syncclient.go, ethstorage/p2p/protocol/types.go, ethstorage/storage_manager.go, ethstorage/storage_manager_test.go
Every time es-node sends a BLOB p2p sync request or a local empty blob-filling, it will send a getKvMetas/getLastKvIdx RPC call. When the RPC latency is high, it will increase a lot of syncing time, and people can check https://github.com/ethstorage/es-node/issues/85 and https://github.com/ethstorage/es-node/issues/86 for more details.
Due to the slow update rate of on-chain blob hashes and lastKvIdx (every two Ethereum mainnet epochs), we can optimize the process by initially downloading them into the local cache before syncing. Subsequently, they can be updated by the downloader every two epochs. This approach allows the peer-to-peer (p2p) sync to directly utilize the local cache, rather than repeatedly making RPC requests, thereby enhancing overall syncing performance.
The …
=> Cache blob metas and lastKvIndex before blob syncing to improve the performance of p2p syncing

.github/workflows/publish.yml, .gitignore, Dockerfile, Makefile, ethstorage/miner/cli.go, ethstorage/miner/config.go, run-docker.sh, run-rpc.sh, run.sh
Replaced https://github.com/ethstorage/es-node/pull/115
1. release zip with scripts and pre-built binaries
2. build a Docker image and push it to  GitHub Container Registry (ghcr.io) on each release
- can be managed in https://github.com/orgs/ethstorage/packages
3. move the built binary (es-node) and snark folders(snarkjs, snarkbuild) to build/bin so that does not depend on src structures.
Note that the corresponding documentation will be changed in https://github.com/ethstorage/es-node/pull/92
=> Build docker image, etc.

README.md, cmd/es-node/config.go, ethstorage/eth/polling_client.go, ethstorage/miner/cli.go, ethstorage/miner/config.go, ethstorage/miner/l1_mining_api.go, ethstorage/miner/worker.go, run.sh
Estimate tx cost and mining reward and compare the profit to the min-profit flag before submitting mining txes.
- implement miner's reward computation based on the logic of the smart contract
- read the actual cost and reward from tx receipt for users to check.
- remove gas price related settings from run.sh so that a market price can be used.
=> Estimate mining profit

ethstorage/p2p/protocol/sync_test.go, ethstorage/p2p/protocol/syncclient.go, ethstorage/storage_manager.go, ethstorage/storage_manager_test.go
related issue: https://github.com/ethstorage/es-node/issues/157
Expected behaviour
CTRL+C should stop es-node immediately during the meta-download phase
How to test:
Start a node and wait until meta-download starts. then CTRL+C to stop the node and the es-node immediately during the meta-download phase.
=> issue157: CTRL+C should stop es-node immediately during meta download phase

ethstorage/eth/heads.go, ethstorage/eth/id.go, ethstorage/miner/algorithm.go, ethstorage/miner/l1_mining_api.go, ethstorage/miner/worker.go, integration_tests/node_mine_test.go
Use RANDAO (`mixDigest` field of the block) as a random seed for hash computing, according to the change of https://github.com/ethstorage/storage-contracts-v1/pull/61.
Tested mining in integration tests with storage contract commit [9775efe](https://github.com/ethstorage/storage-contracts-v1/pull/61/commits/9775efe6fb84029434d87c530f8e5ba77c7ddcf5)
Gas used first time submit 493,167, later 463,305.
Copy old numbers from https://github.com/ethstorage/storage-contracts-v1/issues/20#issuecomment-1879472374 for comparison:
|Circuit|Gas|
|--|--|
|old|572,610|
|new|372,882|
=> Use randao to replace block hash

ethstorage/p2p/protocol/syncclient.go
issue 201: https://github.com/ethstorage/es-node/issues/201
The data syncing and filling-empty speeds may vary significantly, so calculating their respective times would provide a more accurate estimate. This change split the state report into two parts -- sync process and fill empty process. 
How to test:
Run the es-node and see the sync state like the following.
```
INFO [02-05|04:23:44.659] Storage sync in progress                 progress=0.50% peerCount=6 tasksRemain=1@32 blobsSynced=5824@728.00MiB blobsToSync=1,150,778 timeUsed=2m32s etaTimeLeft=8h20m34s
INFO [02-05|04:23:44.659] Storage fill empty in progress           progress=0.54% tasksRemain=1@30 emptyFilled=16368@2.00GiB  emptyToFill=3,021,334 timeUsed=2m32s etaTimeLeft=7h47m37s
```
=> fix issue 201: Syncing time estimation is not accurate

Makefile
Addressing https://github.com/ethstorage/es-node/issues/239
Possible cause: the build was created on a newer version of ubuntu than 20.04 where some dependencies are dynamically linked (GLIBC_2.32, GLIBC_2.34)
Solution:
With CGO_ENABLED=0 you got a statically-linked binary (see: https://en.wikipedia.org/wiki/Static_build) so it will run without any external dependencies
Test has been done on ubuntu 20.04 and 22.04: running es-node till successfully mined.
=> Fix build on Ubuntu 20.04

ethstorage/miner/l1_mining_api.go, ethstorage/miner/worker.go
=> mining stats improvement

ethstorage/flags/p2p_flags.go, ethstorage/p2p/cli/load_config.go, ethstorage/p2p/host.go, ethstorage/p2p/node.go, ethstorage/p2p/protocol/sync_test.go, ethstorage/p2p/protocol/syncclient.go, ethstorage/p2p/protocol/types.go
As we will have more than 100 nodes in the public testnet, we can increase the maxPeers to a larger number like 70 (prysm set this number to 70). 
As the code uses p2p.peers.lo and p2p.peers.hi to set up libp2p connection manager, so when peers count larger than p2p.peers.hi, some connections (peer count - p2p.peers.lo) would disconnect at the same time.
run es-node to join the public testnet, and the peer count joins the local node should not be larger than 70, and when the peer count reaches 70, multi-connections (peer count - p2p.peers.lo) disconnect in a short time.
=> fix issue: inscrease max peers count and use p2p.peers.hi as maxPeers instead

ethstorage/p2p/node.go, ethstorage/p2p/protocol/peer.go, ethstorage/p2p/protocol/syncclient.go, ethstorage/p2p/protocol/utils.go
issue https://github.com/ethstorage/es-node/issues/237
After ctrl + c, the es-node should output "Storage node exited" and stop in a few seconds.
The es-node cannot stop because "host" in NodeP2P failed to stop, that is due to StopNotify in host.Close() blocked by failed to get s.notifs.Lock(). the lock (read lock) is held by notifyAll which calls all the function register through Network.Notify(). And RequestShardList() in the add connection notify function would wait and block the lock, and that is because n.Host().NewStream in that function does not have timeout control. 
github.com\libp2p\go-libp2p\p2p\net\swarm\swarm.go
// StopNotify unregisters Notifiee fromr receiving signals
func (s *Swarm) StopNotify(f network.Notifiee) {
s.notifs.Lock()
delete(s.notifs.m, f)
s.notifs.Unlock()
} …
=> fix issue: es-node cannot stop by ctrl + c

ethstorage/p2p/discovery.go, ethstorage/p2p/protocol/syncclient.go
Update rule: err caused by the remote peer, reduce the log level to info or debug.
=> Reduce log-levels to reduce user confusion

ethstorage/p2p/protocol/peer.go, ethstorage/p2p/protocol/syncclient.go
issue: https://github.com/ethstorage/es-node/issues/261
Fix crashs: add lock ReportPeerSummary and check Peer is null in getIdlePeerForTask
**1. The es-node crash with error log:**
{"log":"panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2024-03-28T18:04:09.789901565Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xe9fab8]\n","stream":"stderr","time":"2024-03-28T18:04:09.789909345Z"}
{"log":"\n","stream":"stderr","time":"2024-03-28T18:04:09.789911745Z"}
{"log":"goroutine 16820 [running]:\n","stream":"stderr","time":"2024-03-28T18:04:09.789913915Z"}
{"log":"github.com/ethstorage/go-ethstorage/ethstorage/p2p/protocol.(*Peer).IsShardExist(...)\n","stream":"stderr","time":"2024-03-28T18:04:09.789916125Z"} …
=> Fix crashs: add lock ReportPeerSummary and check Peer is null in getIdlePeerForTask

ethstorage/miner/miner.go, ethstorage/miner/miner_test.go, ethstorage/miner/worker.go, ethstorage/node/node.go, integration_tests/node_mine_test.go
issue: https://github.com/ethstorage/es-node/issues/253
Added grafana dashboard to overview the network states. this pr is adding mining state types and collecting state for report later.
=> dashboard part 0: Add miner and submission status for network dashboard.

ethstorage/metrics/network_metrics.go, ethstorage/p2p/protocol/syncclient.go
1. For removed nodes, their metrics should be removed from the http://65.109.63.154:9500/, currently all metrics except "ProvidedBlobs" have been removed. "ProvidedBlobs" need to be removed also.
2. When es-node restarts, their state with peerCount will load from DB, but it should be reset to 0 and increased again when new peers join.
=> bug fix - PeerCount is not correct when es-node restart.

ethstorage/flags/p2p_flags.go, ethstorage/p2p/cli/load_config.go, ethstorage/p2p/protocol/peer.go, ethstorage/p2p/protocol/rate.go, ethstorage/p2p/protocol/sync_test.go, ethstorage/p2p/protocol/syncclient.go, ethstorage/p2p/protocol/syncserver.go, ethstorage/p2p/protocol/tracker.go, ethstorage/p2p/protocol/types.go, ethstorage/p2p/protocol/utils.go, run-rpc.sh, run.sh
Issue: https://github.com/ethstorage/es-node/issues/232
Currently, we use p2p.max.request.size to control the size of blobs fetched from peers. However, different peers are distributed in different regions, so the request sizes between the local node and peers should be different. So we should use different request sizes to fetch blobs from different peers.
1. Change the p2p.max.request.size to p2p.request.size which will be used to initialize the request size from a new peer.
2. Add a tracker for each peer to adjust request size according to network conditions between the peer and local node.
capacity = 0.9*(t.capacity) + 0.1* return blobs/second (Return blob count/Return time in second)
3. When selecting an idle peer to send a new request, order idle peers by their capacities, and …
=> fix Issue232: Use dynamically adjusted request size to fetch blobs data from peers through p2p instread of using the static p2p.max.request.size value

ethstorage/p2p/protocol/sync_test.go, ethstorage/p2p/protocol/syncclient.go
unit test TestSaveAndLoadSyncStatus would randomly fail as the syncCl.tasks may not sort by shard id, which is caused by the test case failure. so add sort task after tasks loaded.
=> fix unit test bug: TestSaveAndLoadSyncStatus would randomly fail

ethstorage/p2p/node.go, ethstorage/p2p/protocol/peer.go, ethstorage/p2p/protocol/syncclient.go, ethstorage/p2p/protocol/utils.go
issue 262: https://github.com/ethstorage/es-node/issues/262
**Root Cause**
When creating a newStream to send a request to a peer, if the connection does not exist, it will call the peer again. But if the address of that peer does not exist, this issue will be thrown.
The peer address does not exist because of time-to-live timeout, which is 24 hours correctly. time-to-live timeout means the peer not be added back to peerstore by discovery.
pstore.AddAddrs(info.ID, info.Addrs, discoveredAddrTTL) // discoveredAddrTTL = time.Hour * 24
**How to fix it**
Change the log level to debug for the error caused by newStream "no addresses" and close the peer.
=> fix issue 262: close peers that have no addresses in the host.peerstore due to expired ttl.

cmd/es-node/config.go, ethstorage/eth/polling_client.go, ethstorage/eth/randao_client.go, ethstorage/flags/flags.go, ethstorage/miner/l1_mining_api.go, ethstorage/miner/miner_test.go, ethstorage/miner/worker.go, ethstorage/node/config.go, ethstorage/node/node.go, integration_tests/node_mine_test.go, run-l2.sh, run.sh
For the miner to read Randao from L1 blocks, add a polling client to sync the latest L1 block number known by the L2 by calling `L1Block` contract.
=> L2 support miner change

.github/workflows/publish.yml
Copied from [here](https://github.com/ethereum-optimism/optimism/blob/develop/.github/workflows/release.yml#L9), it seems good practice to follow.
=> add `concurrency` to release workflow

run-l2-rpc.sh, run-rpc.sh
The default value of `rpc.addr` is 127.0.0.1, which can’t serve external requests. It needs to be set to 0.0.0.0.
=> The RPC service needs to be public when running the RPC script.

ethstorage/downloader/downloader.go
The very long finalization time on L2 (12 hours) breaks our initial assumption about `downloadToCache`. Therefore, we may need to batch download the BLOB to cache in case there are too many events emitted from the storage contract and the es-node can’t handle them all at once.
=> Batch download into cache

ethstorage/miner/miner_test.go
Fake a zkey file to satisfy the check in `NewKZGPoseidonProver`
=> fix miner test

ethstorage/miner/algorithm.go, ethstorage/miner/algorithm_test.go, ethstorage/miner/worker.go
Addressing https://github.com/ethstorage/es-node/issues/304.
The current `expectedDiff()` in es-node differs from the implementation in MiningLib.sol, leading to rare cases where the computed difficulty does not match.
The unit test utilizes actual input data including previously failed cases.
reference:
=> Fix 'diff not match'

ethstorage/p2p/node.go, ethstorage/p2p/notifications.go
Connection is filtered out when n.host.Peerstore().Addrs(remotePeerId)) == 0. which is added to fix issue https://github.com/ethstorage/go-ethstorage/issues/72. (related PR: https://github.com/ethstorage/go-ethstorage/pull/91)
However, this fix will additionally filter out some connections that should not be ignored. For example, if a connection is coming in connection (Direction == DirInbound), its address may not have been added to Peerstore yet, at this time, the incoming connection would be ignored. The following are the connections shown when stopping the es-node, but only 29 of them are added to the syncclient.
**How to Fix**
To ignore the connection without disconnecting which is caused by NAT, this can be done after we get the shard list failure. 
After the change, we will get the …
=> fix bug: connection with DirInbound may not have addresses in Peerstore.

ethstorage/node/eth_api.go
__Issue to address__
While stored as blobs, some big web resources cannot be loaded thru the web3 gateway, which the console shows:
```
ERRO[2024-09-14 10:11:59] FetchUrl error: internal server error: Post "http://127.0.0.1:8545": context deadline exceeded  
```
__root cause__
The default timeout is too short so the es-node does not have enough time to make eth_esCall to es_geth.
__solution__
The solution is to extend the timeout.
=> RPC timeout update

.github/workflows/integration-test.yml
Currently, the test logs will be removed after a new integration test starts, add the `upload logs` step to the Integration test to upload them all. After the change, the action page will show the logs as follows:
=> add upload logs to Integration test action

.github/workflows/integration-test.yml
Currently, the integration-test notification job will fail with the error "Connection timeout" as it runs on self-hosted. 
So change the integration test's notification job to run on ubuntu-latest.
https://github.com/ethstorage/es-node/actions/runs/11443530042 ()
=> update integration test run-on to ubuntu-latest for notification job

.github/workflows/alerting.yml, cmd/alert/main.go
Add alert action to check ethstorage servers. Action will be run every hour; no need to maintain a separate server. If more states need to be checked, add a function like `checkLastMinedBlock `to output alert content if an alert is needed.
=> Add alert action to check ethstorage state

cmd/integration-test-server/main.go, ethstorage/miner/worker.go
Currently, two failures ("diff not match" and "invalid samples") are by-design failures, which should not cause the integration test to fail. So, when the mining failure count is larger than 0, the code will check whether those failures are by design or not. 
Log errors and remove them from the failure count if they are by design.
=> Add check by design failure check to integration test

ethstorage/miner/l1_mining_api.go
Fixes https://github.com/ethstorage/es-node/issues/332.
The issue happens when the latest version of es-node calls `miningReward` method of the storage contract before submitting the mining transaction.
The root cause is in the earlier version of the storage contract, the function `miningReward` uses the wrong `block.timestamp` and `block.number` to compute the mining timestamp in the L2 network, which may cause an underflow of unit.
The solution would be instead of aborting the transaction upon the error from `miningReward`, to use a marketable gas price, which is independent of the reward, to submit the tx anyway.
Tests been done: using a storage contract that can reproduce the error, applying the fix to the es-node can submit the tx successfully while getting a failed warning from …
=> Fix `arithmetic underflow or overflow`

cmd/integration-test-server/main.go
The [integration test](https://github.com/ethstorage/es-node/actions/runs/12026631901) fails with a known issue, which our pattern has not been covered. Updated our pattern to cover it.
In the previous pattern, when we mined a block with an empty blob, if the blob content was updated before "Got storage proof", we expected this mining result to fail as the blob was updated. Otherwise, we will expect the mining will succeed.
Because, after the miner "Got storage proof", we consider mining to be over and submit the mining transaction immediately. As the time between "Got storage proof" and submitting transactions is relatively short. The previous pattern believed that the possibility of data updating during this period was very small and could be ignored. 
The reason why the integration …
=> Fix integration test

ethstorage/archiver/guide-sepolia.md, integration_tests/run_tests.sh
Tutorial doc to add an op-node to rollup testnet using Sepolia as L1. The purpose is to test derivation correctly from ES archive service. (Milestone 4)
=> Archiver test doc on Sepolia

ethstorage/archiver/guide-blob-test.md, ethstorage/archiver/guide-devnet.md
Fix comments during the demo. Major changes include:
- Reorg the table of contents
- Move the es-node setup to a later point to compare results with and without the archive service.
- Correct the incorrect command
- Update the beacon-api-wrapper to use epoch as the unit of retention time (per EIP-4844, which defines the retention period as 4096 epochs).
- Address inconsistencies in titles, etc.
Changes verified in the test environment.
=> Archiver test doc update

docs/archiver/archiver-guide-devnet.md
Hi,
I just found a typo in this text and suggest correction.
'retreive' should be 'retrieve'.
Not much but it's honest work.
Thanks.
=> Typo in: Update archiver-guide-devnet.md

run-l2.sh
Fix the error when running `run-l2-rpc.sh`: 
```
$ ./run-l2-rpc.sh
========== build info ==================
EthStorage node version v0.1.16-f533a6fc-1735115453
Build date: Wed Dec 25 16:54:09 CST 2024
System version: amd64/darwin
Golang version: go1.22.3
========================================
t=2024-12-25T16:57:28+0800 lvl=info msg="Configuring EthStorage Node"
INFO [12-25|16:57:28.260] Read L1 config                           l1.rpc=http://5.9.87.214:8545
INFO [12-25|16:57:28.260] Read L1 config                           l1.beacon=http://88.99.30.186:3500
INFO [12-25|16:57:28.260] Loaded storage config                    l1Contract=0x64003adbdf3014f7E38FC6BE752EB047b95da89A miner=0x0000000000000000000000000000000000000000
INFO [12-25|16:57:28.857] Read uint from contract …
```
=> Fix missing slash of l2 script

cmd/dashboard/config.json, cmd/dashboard/main.go, ethstorage/metrics/metrics.go
We currently use a contract address to differentiate between different networks, but different networks would still use the same one. So add chain ID ahead of contract address to differentiate different networks.
=> Dashboard: add chainID to contract address for dashboard

ethstorage/archiver/config.go, ethstorage/archiver/service.go, ethstorage/archiver/utils.go, ethstorage/archiver/utils_test.go
Fixes issue https://github.com/ethstorage/es-node/issues/363
The code change refers to prysm [here](https://github.com/prysmaticlabs/prysm/blob/ecf5a368d78dadcb3bd7c19d0d723a3d4f034989/beacon-chain/rpc/eth/blob/handlers.go#L100) and [here](https://github.com/prysmaticlabs/prysm/blob/ecf5a368d78dadcb3bd7c19d0d723a3d4f034989/api/server/middleware/util.go#L9).
Tests: 
Now the URL works: http://65.108.236.27:9645/eth/v1/beacon/blob_sidecars/6650418?indices=0&indices=1&indices=2&indices=3&indices=4
=> Fix archiver: repeated params are not supported

cmd/es-node/main.go, cmd/es-node/utils.go, ethstorage/storage_manager.go, ethstorage/storage_manager_test.go, sync.sh
An es-node subcommand to download a blob from an RPC node and update it in local storage. This tool can fix a data entry that was accidentally incorrect.
Usage example:
```bash
env ES_NODE_STORAGE_MINER=0x4b07e60490BE95c03d41F63203De9b51657A4C1a ./sync.sh --kv_index=2012299
```
The hash can be checked and verified using:
```bash
cd cmd/es-utils
go build
./es-utils meta_read --filename ../../es-data/shard-0.dat  --kv_idx=2012299  --kv_entries=8192 --kv_size 131072 --chunk_size 131072
```
incorrect  hash
>01abcdf2f4528e806a2a89c452e1c38209180dfd4db4a8c08000000000000000
correct hash
>01aa945c93ead8b4630b48e3b380864b0c663c2383a4d6d48000000000000000
=> es-node tool to fix a specific kv entry

.github/workflows/publish.yml, Dockerfile
Fix the issue that the l2 scripts are not included in pre-built binaries.
Tests have been done on ax101, where the `init-l2.sh` and `run-l2.sh` in the prebuilt were successfully executed to sync data and sampling in the SWC testnet.
Same tests done to Docker releases.
=> fix swc build

ethstorage/p2p/node.go, ethstorage/p2p/protocol/sync_test.go, ethstorage/p2p/protocol/syncclient.go
Add FetchBlob to SyncClient to support fetching a single blob from the network via p2p, it will use by [pr 392](https://github.com/ethstorage/es-node/pull/392/files).
interface: 
func FetchBlob(index uint64, commit common.Hash) ([]byte, error)
=>  Add FetchBlob to SyncClient to support fetching a single blob from the network via p2p

docs/archiver/archiver-guide-blob-test.md
This PR fixes a small formatting issue in the EthStorage Archive Service documentation. It removes extra spaces after "es-node" in the setup commands `./init-rpc.sh` and `./run-rpc.sh`, making the documentation more accurate for users following the setup instructions.
=> Fix typo in setup commands by removing extra spaces

ethstorage/eth/polling_client.go, ethstorage/miner/l1_mining_api.go, ethstorage/node/node.go
Check if the miner is in the miner's role (whitelisted) when es-node is started.
Tests have been done when starting es-node:
Based on storage contract version:
**v0.1.1**
ignore role check
**v0.1.2**
Happy paths:
-  Miner role enforced / Miner role granted
-  Miner role not enforced
Failed to start es-node:
-  Miner role enforced / Miner role not granted
=> check miner role

ethstorage/p2p/protocol/syncclient.go, ethstorage/prover/merkleprover.go, ethstorage/scanner/worker.go, ethstorage/storage_manager.go
In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.
Inspired by https://github.com/ethstorage/es-node/pull/396 and I replace all of the case.
=> refactor: use the built-in max/min to simplify the code
