ethstorage/es-node

- Dockerfile
- GUIDE.md
- README.md
- cmd/es-node/main.go
- run-docker.sh
- run.sh
Some fix/updates based on devnet1 test feedback:
- Dockerfile: cache dependencies
- README: note go1.21 not supported.
- GUIDE: use https for public repo
- cmd/es-node/main.go: check address before use
- sh scripts: check environment variables passed in.
- run.sh: check init result before launch node
> Validate miner address and other updates

- GUIDE.md
- ethstorage/miner/worker.go
1. Doc: specifically checkout branch 
2. miner: address log issue: https://github.com/ethstorage/es-node/issues/87
> Improve log, etc.

- ethstorage/miner/config.go
Addresses https://github.com/ethstorage/es-node/issues/96
> Double default threads for mining

- .github/workflows/publish.yml
- GUIDE.md
address https://github.com/ethstorage/es-node/issues/84
Leave the doc update to https://github.com/ethstorage/es-node/pull/92
> Add github workflow to release with pre-build versions of es-node

- ethstorage/miner/l1_mining_api.go
- ethstorage/miner/miner.go
- ethstorage/miner/worker.go
Expose miningInfo Attributes to other packages, this will used by the dashboard service.
> expose miningInfo Attributes to other package

- GUIDE.md
> improve guide

- .github/ISSUE_TEMPLATE/ask-a-question.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/request-a-feature.md
Refer to geth repo: https://github.com/ethereum/go-ethereum/issues/new/choose
> Update issue templates

- ethstorage/node/node_test.go
- ethstorage/p2p/protocol/sync_test.go
related issue: https://github.com/ethstorage/es-node/issues/76
> Fix unit test execution failed for node and sync

- ethstorage/node/eth_api.go
- ethstorage/node/node.go
- ethstorage/node/server.go
Related to https://github.com/ethstorage/es-node/issues/172
> RPC uses l2ChainId which can be set using ---l2.chain_id

- run.sh
Fix https://github.com/ethstorage/es-node/issues/174
> check snarkjs installation

- run.sh
Rewrite the part so that both can work
> Rewrite shell to be readable to Docker container

- ethstorage/node/node.go
- ethstorage/p2p/node.go
- ethstorage/p2p/protocol/sync_test.go
- ethstorage/p2p/protocol/syncclient.go
bug: initDatabase does not return an error when rawdb.Open fail.
> small change - fix bug, rename, fix typo

- cmd/dashboard/main.go
related issue: https://github.com/ethstorage/es-node/issues/211
The cost value in Grafana is from transactions which is more like an estimated result, we should change to use the value calculated from receipt GasUsed * EffectiveGasPrice.
> fix bug: Grafana dashboard Cost value is not match with the value in etherscan.io

- run-rpc.sh
- run.sh
Replace the RPC endpoint hosted by QuickNode with self-hosted RPC
> Self hosted RPC node

- GUIDE.md
related issue: https://github.com/ethstorage/es-node/issues/182
es-node can be run in Windows using WSL, add related info to GUIDE.md.
> add document for windows

- cmd/dashboard/main.go
the GasFee and Reward in the miningEvent struct may be larger than max uint64 during the calculation, change the type to big.int.
> Fix potential data overflow issue in the dashboard service

- cmd/es-node/main.go
- cmd/es-utils/utils/utils.go
- integration_tests/kzg_prover_test.go
- run.sh
For public testnet 1：
1. new zkey with trust setup
2. prompt version
3. update data gas on Sepolia
4. let go of estimate gas because blobhash fails to be estimated
5. debug msg
> replace zkey

- Dockerfile
- run.sh
Dockerfile changed to support bash. Otherwise run.sh will report the error "bad substitution" in the logic of evaluating a flag.
> Rpc override

- run.sh
> fix zkey link

- ethstorage/storage_manager.go
> Level up commit blob failed error

- run.sh
- Check nodejs installation before too late, addressing https://github.com/ethstorage/es-node/issues/256
- Check installation result of snarkjs
> Node check

- ethstorage/p2p/node.go
- ethstorage/p2p/protocol/sync_test.go
- ethstorage/p2p/protocol/syncclient.go
- ethstorage/p2p/protocol/syncserver.go
- ethstorage/p2p/protocol/task.go
- ethstorage/p2p/protocol/types.go
- ethstorage/storage_manager.go
issue: https://github.com/ethstorage/es-node/issues/253
To add grafana dashboard to overview the network states and this pr is adding sync state types and collecting state for network dashboard report later.
> dashboard part 1: add sync state and collect data for network dashboard

- run-l2.sh
Apply the updates of `run.sh`  in https://github.com/ethstorage/es-node/pull/281 to `run-l2.sh`
> Fix L2 run script

- run-l2-rpc.sh
- run-l2.sh
> L2 testnet

- .github/workflows/integration-test.yml
Added a notification job to the Integration test to send emails to related people. After the workflow is done, we will receive emails like the following:
> Add notification job to Integration test to send email to related people.

- .github/workflows/integration-test.yml
Add workflow_dispatch to the integration test action so that it can be triggered manually.
>  Add workflow_dispatch to the integration test action so that it can be triggered manually

- cmd/es-node/main.go
> Prompt version to v0.1.16

- cmd/priv-dashboard/main.go
Add checkState before reporting node state. otherwise, the invalid node state would cause the server to crash.
> Add checkState before reporting node state.

- cmd/priv-dashboard/main.go
- cmd/priv-dashboard/test/main.go
- ethstorage/metrics/network_metrics.go
- ethstorage/node/node.go
- ethstorage/node/state.go
Add contract address to filter whether networks are from Sepolia or l2.
1. Add contract address to metrics to filter in the grafana
2. Add a test client to upload fake data
3. Add contracts Variable to Grafana dashboard to filter the network, and update the dashboard to support it.
>  Add contract address to filter whether networks are from Sepolia or l2.

- ethstorage/archiver/guide-blob-test.md
Guide to test random blob using archive service, addressing milestone 3.
> Guide to test random blob using archive service

- ethstorage/archiver/guide-devnet.md
Fix
- Some grammar issues
- Incorrect inbox contract deployment script
- Bash comment should be '#' rather than '//'
- Run 'npm run install:all'
> Fix long term DA tutorial

- init-l2.sh
- run-l2.sh
Need to upldate init-l2-rpc.sh, run-l2-rpc.sh (@iteyelmp ), run-l2-it-rpc.sh, run-l2-it.sh (@ping-ke ) accordingly.
> Boot node and RPC for L2 beta testnet

- cmd/alert/rules.json
- integration_tests/scripts/ituploader.js
- run-l2-it-rpc.sh
- run-l2-it.sh
Similar change: https://github.com/ethstorage/es-node/pull/350
> update RPC to L2 beta testnet for integration test and alerting action 

- cmd/dashboard/config.json
- cmd/dashboard/l2receipt.go
- cmd/dashboard/main.go
- ethstorage/metrics/metrics.go
Change Dashboard -- grafana.ethstorage.io to show multi-chain mining info
Changes:
1. Add config file
2. Support L2 receipt to calculate L2 TX cost
3. Update es-node Metrics to show the contract address to the metrics data
4. Update dashboard service to fetch mining info from multi-chains
5. Update https://grafana.ethstorage.io/ to add the contract address as a filter 
https://grafana.ethstorage.io/
> Change Dashboard -- grafana.ethstorage.io to show multi-chains' mining infos

- cmd/alert/main.go
- cmd/alert/rules.json
Removed Galileo related alerts from alert config, as the Galileo network will be deprecated soon.
> Removed Galileo related alerts from alert config, as the Galileo network will be deprecated soon.

- cmd/es-node/main.go
> bump version to v0.1.17

- run-l2.sh
We need to generate new ENR since l2 chain id is added into it in https://github.com/ethstorage/es-node/pull/355
> New ENR due to https://github.com/ethstorage/es-node/pull/355

- run.sh
> New ENR for EthStorage bootnode on Sepolia

- Dockerfile
Make the versions in Docker and go mod consistent
> Pump go version in Docker

- ethstorage/miner/worker.go
- ethstorage/p2p/protocol/peer.go
- ethstorage/p2p/protocol/tracker.go
- integration_tests/node_mine_test.go
> chore: fix some typos

- ethstorage/downloader/downloader.go
https://github.com/ethstorage/es-node/issues/382
The downloader (DownloadFinished function) writes BLOBs to the storage file in parallel. Although the BLOBs array passed to this function maintains the correct order, concurrent write operations can result in an earlier update being overwritten by a later one. In this case, the second update was written first, but then the first update overwrote it, leading to incorrect data storage.
To resolve this issue, we ensure that before calling the DownloadFinished function, all key-value indices (kvIndices) are unique. In other words, if multiple updates exist for the same key-value pair within a block, only the last update is written to the storage file.
1. Setup:
- Deployed a new storage contract on Sepolia.
- Ran a new es-node connected to the …
> Fix the race condition issue when writing the downloaded BLOB into the storage file

- cmd/es-node/utils.go
remove duplicate package imports
> chore: remove duplicate package imports

- sync-l2.sh
As part of https://github.com/ethstorage/es-node/pull/381, for L2.
> sync script for l2

- init.sh
Due to zkey files relocation. 
Also make build and create folders if not yet.
> Change zkey download urls

- cmd/dashboard/main.go
- cmd/integration-test-server/main.go
- cmd/priv-dashboard/main.go
- ethstorage/archiver/blob.go
- ethstorage/downloader/blob_cache_test.go
Optimize code using a more modern writing style. Official support by Go Team. https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.
> refactor: replace []byte(fmt.Sprintf) with fmt.Appendf

- ethstorage/miner/l1_mining_api.go
- ethstorage/miner/utils.go
- ethstorage/node/node.go
With this PR, the error message will be easier to understand. For example,
Previous error message:
> failed to estimate gas: execution reverted: ErrorData: 0x5bae1031
After this PR:
> failed to estimate gas: execution reverted: ErrorData: 0x5bae1031: StorageContract_MinerNotWhitelisted()
> Translate error message from calling contract

- ethstorage/downloader/blob_disk_cache.go
- ethstorage/miner/cli.go
- ethstorage/miner/config.go
- ethstorage/miner/l1_mining_api.go
- ethstorage/miner/l1_mining_api_test.go
- ethstorage/miner/utils.go
- ethstorage/miner/worker.go
- ethstorage/scanner/scanner.go
- ethstorage/scanner/worker.go
Drop tx if gas price is higher than a max gas price configured by `--miner.max-gas-price`.
And cut down a few logs.
> Drop tx for high gas price

- cmd/es-node/main.go
- ethstorage/flags/flags.go
Update usage texts to look more user-friendly in ES docs.
> Help updates
